pywww/main/urls.py
from django.urls import path
from main.views import hello_world, contact_us

app_name = 'main'
urlpatterns = [
    path('', hello_world, name='hello_world'),
    path('contact_us', contact_us, name='contact_us'),
]

pywww/posts/urls.py
from django.urls import path
from posts.views import posts_list, posts_details, add_post_form, toggle_sponsored
app_name = "posts"
urlpatterns = [
   path('', posts_list, name='list'),
   path('<int:id>', posts_details, name='details'),
   path('add', add_post_form, name='add'),
   path('toggle_sponsored', toggle_sponsored, name='toggle_sponsored')
]

pywww/pywww/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('', include('main.urls')),
                  path('posts/', include('posts.urls')),
                  path('admin/', admin.site.urls),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)\
                + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pywww/main/models.py
from django.db import models

# Create your models here.
class UserProfile(models.Model):
   user = models.OneToOneField("auth.User", on_delete=models.CASCADE)
   bio = models.TextField()

   def __str__(self):
      return f'Profile for {self.user} : {self.bio[:30]}...'

pywww/posts/models.py
from django.db import models
from django.utils.timezone import now, timedelta


class CheckAgeMixin:
    def is_older_than_n_days(self, n=1):
        """Check if created is older than now() - n days"""
        delta = timedelta(days=n)
        return now() - self.created > delta


class Timestamped(models.Model, CheckAgeMixin):
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


# Create your models here.
class Post(Timestamped):
    author = models.ForeignKey(
        "auth.User",
        on_delete=models.CASCADE,
        related_name="posts"
    )
    title = models.CharField(max_length=255)  # pole tekstowe o określonej długości
    content = models.TextField()  # pole tekstowe o nieokreślonej długości
    published = models.BooleanField(default=False)  # flaga true/false
    created = models.DateTimeField(auto_now_add=True)  # data utworzenia - tylko przy utworzeniu
    modified = models.DateTimeField(auto_now=True)  # data modyfikacji - zawsze gdy klikniemy save
    tags = models.ManyToManyField('tags.Tag', related_name="posts")
    example_file = models.FileField(upload_to='posts/examples/', blank=True, null=True)
    image = models.ImageField(upload_to='posts/images/', blank=True, null=True)
    sponsored = models.BooleanField(default=False)


    def is_content_long(self, n_chars=200):
        # napisać metode modelu odpowiadającą na pytanie czy post jest długi.
        # długie posty w szablonie szczgółów skracamy do 200 znaków i dodajemy ...
        return len(self.content) > n_chars

    def short_content(self, n=200):
        return self.content[:n]

    def __str__(self):
        return f'{self.title} by {self.author}'

pywww/tags/models.py
from django.db import models
from django.utils.text import slugify

# Create your models here.
class Tag(models.Model):
   name = models.CharField(unique=True, max_length=100)
   slug = models.SlugField(unique=True, max_length=100)

   def save(self, *args, **kwargs):
      if not self.slug:
         n = self.name
         s = slugify(n)
         print(f'Autogeneracja sluga: {n} -> {s}')
         self.slug = s
      return super().save(*args, **kwargs)

   def __str__(self):
      return self.slug

pywww/main/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit, Layout, Fieldset, HTML, ButtonHolder
from django import forms


class ContactForm(forms.Form):
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control'}))
    title = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    content = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control'}))
    send_to_me = forms.BooleanField(required=False, widget=forms.CheckboxInput(attrs={'class': 'form-check-input'}))

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.form_action = 'contact_us'
        self.helper.add_input(Submit('submit', 'Wyślij'))

        # self.helper.layout = Layout(
        #     Fieldset('Dane kontaktowe', 'email'),
        #     Fieldset('Zawartość', 'title', 'content'),
        #     Fieldset('Dodatkowe',HTML("Zaznacz jeśli chcesz by wysłać kopię wiadomości do Ciebie"),'send_to_me',),
        #     ButtonHolder(Submit('submit', 'Wyślij', css_class='btn btn-primary'),css_class="d-flex justify-content-end")
        # )

pywww/main/views.py
from pprint import pprint

from django.shortcuts import render
from django.http import HttpResponse, HttpRequest
from django.shortcuts import render, redirect
from main.forms import ContactForm

# Create your views here.



def hello_world(request: HttpRequest):
    context = {}
    return render(request, 'main/hello.html', context)


def contact_us(request):
#     context = {'form': ContactForm()}
#     return render(request, 'main/contact_us.html', context)
#
# def contact(request):
   if request.method == "POST":
       form = ContactForm(data=request.POST)
       if form.is_valid():
           print(form.cleaned_data)
           return redirect('main:hello_world')
   else:
       print('invalid')
       form = ContactForm()
   return render(
       request,
       "main/contact_us.html",
       {"form": form}
   )

pywww/posts/views.py
import os
# from django.http import HttpResponse
from pprint import pprint
from tags.models import Tag

from django.http import HttpResponse
from django.contrib.auth.models import User
from posts.models import Post
# from django.template import loader
from django.shortcuts import render
from django.shortcuts import render, redirect


def posts_list(request):
    q = title__contains = request.GET.get('q')
    lista_postow = Post.objects.all()
    if q:
        lista_postow = lista_postow.filter(title__contains=q)
    context = {
        'posts_list': lista_postow,
    }
    return render(request, 'posts/list.html', context)


def posts_details(request, id):
    post = Post.objects.get(id=id)
    context = {'post': post}
    return render(request, 'posts/details.html', context)


def add_post_form(request):
    if request.method == "POST":
        data = {
            "title": request.POST['title'],
            "content": request.POST['content'],
            "published": 'published' in request.POST,
            "author": request.POST['author'],
        }
        post = Post.objects.create(**data)
        for tag_id in request.POST.getlist('tags'):
            tag_id = int(tag_id)
            t = Tag.objects.get(id=tag_id)
            post.tags.add(t)
        return redirect('posts:list')

    else:
        tags = Tag.objects.all()
        return render(request, 'posts/add.html', {"tags": tags})


def add_post_form(request):
    if request.method == "POST":
        data = {
            "title": request.POST['title'],
            "content": request.POST['content'],
            "published": 'published' in request.POST,
            "author": User.objects.get(id=request.POST['author'])
        }
        post = Post.objects.create(**data)
        for tag_id in request.POST.getlist('select'):
            tag_id = int(tag_id)
            t = Tag.objects.get(id=tag_id)
            post.tags.add(t)
        return redirect('posts:list')
    else:
        context ={
            'tags': Tag.objects.all(),
            'authors': User.objects.all()
        }
        return render(request, 'posts/add.html', context)

def toggle_sponsored(request, id):
    post = Post.objects.get(id=id)
    post.sponsored = not post.sponsored
    post.save()
    return redirect('posts:list')

pywww/tags/views.py
from django.shortcuts import render

# Create your views here.

pywww/main/templates/main/base.html
{% load static %}
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
        "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
    <title>
        {% block title %}{% endblock %}
    </title>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
</head>
<style>

</style>

<body>

<img src="{% static "main/img/logo1.png" %}" width="25" height="30">


<span class="badge text-bg-primary"><a href="{% url 'main:hello_world' %}" class="link-light">Strona główna</a></span>
<span class="badge text-bg-primary"><a href="{% url 'main:contact_us' %}" class="link-light">Kontakty</a></span>
<span class="badge text-bg-primary"><a href="{% url 'posts:list' %}" class="link-light">Posty</a></span>
<span class="badge text-bg-primary"><a href="{% url 'posts:add' %}" class="link-light">Dodaj post</a></span>

{% block content %}{% endblock %}
<h6>To jest stopka całego serwisu</h6>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
</body>
</html>

pywww/main/templates/main/contact_us.html
{% extends "main/base.html" %}
{% load crispy_forms_tags %}
{% block title %}Kontakt{% endblock %}
{% block content %}
    {% crispy form form.helper %}
{% endblock %}

pywww/main/templates/main/contacts.html
{% extends "base.html" %}
{% block title %}Kontakt{% endblock %}
{% block content %}
   <form method="POST">
       {% csrf_token %}
       {{ form }}
   </form>
{% endblock %}

pywww/main/templates/main/hello.html
{% extends "main/base.html"%}
{% block title %}Strona główna{% endblock %}
{% block content %}
<p>Witamy w serwisie</p>

{% for post in posts_list %}
{% if post.published %}

<div class="card" style="width: 18rem;">
    <img src="..." class="card-img-top" alt="...">
    <div class="card-body">
        <h5 class="card-title">{{post.title}}</h5>
        <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's
            content.</p>
        <a href="#" class="btn btn-primary">Go somewhere</a>
    </div>
</div>
{% endif %}#}
{% endfor %}
{% endblock %}

pywww/posts/templates/posts/add.html
{% extends "main/base.html" %}
{% block title %}Dodawanie postu{% endblock %}
{% block content %}

<form method="POST">
    {% csrf_token %}
    <div class="mb-3">
        <label for="title" class="form-label">Post title</label>
        <input type="text" class="form-control" id="title" name="title" placeholder="Wpisz tytuł postu">
    </div>

    <select class="form-select" aria-label="Author" id="author" name="author">
        {% for author in authors %}
  <option value="{{ author.id }}">{{ author }}</option>
 {% endfor %}
</select>

    <select class="form-select" multiple aria-label="multiple select example" name="select">
        {% for tag in tags %}
                    <option value="{{ tag.id }}">{{ tag.name }}</option>
                {% endfor %}
</select>
    <div class="mb-3">
        <label for="content" class="form-label">Post text</label>
        <textarea class="form-control" id="content" rows="3" name="content" placeholder="Wpisz tekst postu"></textarea>
    </div>
    <div class="form-check">
        <input class="form-check-input" type="checkbox" value="on" id="published" name="published">
        <label class="form-check-label" for="published">
            Is post published?
        </label>
    </div>
    <button type="submit" class="btn btn-primary">Save</button>

</form>

<!-- Button trigger modal -->
<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
  Launch static backdrop modal
</button>

<!-- Modal -->
<div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="staticBackdropLabel">Modal title</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <form method="POST">
    {% csrf_token %}
    <div class="mb-3">
        <label for="title" class="form-label">Post title</label>
        <input type="text" class="form-control" id="title" name="title" placeholder="Wpisz tytuł postu">
    </div>

    <select class="form-select" aria-label="Author" id="author" name="author">
        {% for author in authors %}
  <option value="{{ author.id }}">{{ author }}</option>
 {% endfor %}
</select>

    <select class="form-select" multiple aria-label="multiple select example" name="select">
        {% for tag in tags %}
                    <option value="{{ tag.id }}">{{ tag.name }}</option>
                {% endfor %}
</select>
    <div class="mb-3">
        <label for="content" class="form-label">Post text</label>
        <textarea class="form-control" id="content" rows="3" name="content" placeholder="Wpisz tekst postu"></textarea>
    </div>
    <div class="form-check">
        <input class="form-check-input" type="checkbox" value="on" id="published" name="published">
        <label class="form-check-label" for="published">
            Is post published?
        </label>
    </div>
    <button type="submit" class="btn btn-primary">Save</button>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Understood</button>
      </div>
    </div>
  </div>
</div>
{% endblock %}

pywww/posts/templates/posts/details.html
{% extends "main/base.html" %}
{% block title %}Szczegóły postu{% endblock %}
{% block content %}
    <div class="card" style="width: 40rem;">
         {% if post.image %}
                <img src="{{post.image.url}}" class="card-img-top" alt="...">
            {% endif %}
        <div class="card-body">
            <h5 class="card-title">Tytuł posta: {{ post.title }}</h5>
            <h6 class="card-title">Autor posta: {{ post.author }}</h6>
        </div>
        <ul class="list-group list-group-flush">

            {% if post.is_content_long %}
                <li class="list-group-item">Shortened: {{ post.short_content }}...</li>
            {% else %}
                <li class="list-group-item">{{ post.content }}</li>
            {% endif %}
            <li class="list-group-item">{{ post.created }}</li>
            <li class="list-group-item">{{ post.modified }}</li>
            <li class="list-group-item">
                {% for tag in post.tags.all %}
                <span class="badge rounded-pill text-bg-secondary">{{ tag.slug }}</span>

                {% endfor %}
            </li>
            {% if post.image %}
                <li class="list-group-item">Pobierz <a href="{{ post.image.url }}">przykład</a></li>
            {% endif %}

        </ul>
        <div class="card-body">
            <a href="#" class="card-link">Powrót do listy postów</a>
        </div>
    </div>


{% endblock %}

pywww/posts/templates/posts/list.html
{% extends "main/base.html"%}
{% block title %}Lista postów{% endblock %}
{% block content %}
<div class="container text-left">
    <div class="row">
        <form>
            <input type="text" id="q" name="q">
            <input type="submit" value="search">
        </form>
    </div>



    {% for post in posts_list %}

    <div class="row">
        <div class="col-6">
            {% if post.sponsored %}
            <a href="{% url 'posts:details' post.id %}"><mark>{{ post.title}}</mark></a>

            {% else %}
             <a href="{% url 'posts:details' post.id %}">{{ post.title}}</a>
              {% endif %}
        </div>
        <div class="col">
            {{post.created | date:"d-m-Y H:i"}}
        </div>
        <div class="col">
            {% if post.sponsored %}
            <span class="badge text-bg-primary"><a href="{% url 'posts:list' %}" class="link-light">SPONSOROWANY</a></span>
            {% else %}
            <button type="button" class="btn btn-secondary"><a href="{% url 'posts:toggle_sponsored' %}" class="link-light">sponsoruj</a></button>
            <a href="#" class="btn btn-primary" role="button" data-bs-toggle="button">Toggle link</a>
            {% endif %}
        </div>
    </div>
    {% endif %}

    {% endfor %}

    {% endblock %}